---
- name: install monit 
  yum: name=redis state=latest
- name: copy monit.conf
  copy: src=monit.conf dest=/etc/monit.conf force=yes
  notify: 
   - restart monit

- name: enable on boot 
  service: name=monit state=started enabled=yes 

- name: open port from anywere 
  lineinfile: dest=/etc/redis.conf regexp='^bind' line="bind 0.0.0.0" state=present

- name: setup monit
  copy: src=redis.monit dest=/etc/monit.d/redis force=yes
  notify: restart monit
