---
- name: install nginx repo 
  shell: rpm -ivh --force http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm 

- name: install nginx 
  yum: name=nginx state=latest

- name: copy nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644

- name: copy index.html to make this 404 
  copy: src=index.html dest=/usr/share/nginx/html/index.html mode=0644 

- name: create default config for application
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  tags:
    - update_config

- name: copy monit config for nginx
  copy: src=monit.nginx dest=/etc/monit.d/nginx force=yes
  notify: restart monit


   
       
