---
- name: create user traberry
  user: name=traberry

- name: create ~/traberry/.ssh
  sudo: yes
  sudo_user: traberry
  file: path=/home/traberry/.ssh state=directory owner=traberry group=traberry mode=0700

- name: copy ops key to traberry
  copy: src=/home/ops/.ssh/id_rsa dest=/home/traberry/.ssh/id_rsa owner=traberry group=traberry mode=0600

- name: install Mysql package for module
  yum: name={{item}} state=latest
  with_items:
    - gcc
    - libxml2-devel
    - mysql-devel
    - expat-devel
    - redis

# YOU MAY NEED TO RUN MANUALLY BELOW
#- name: install perl with perlenv 
#  sudo: yes
#  sudo_user: traberry
#  script: perlenv.sh

- name : copy monit config for traberry
  copy: src=traberry_monit.conf dest=/etc/monit.d/traberry.conf
  notify: 
   - restart monit

- name: obtain source from github
  git: repo=git@github.com:shohey1226/TraBerry.git 
       dest=/home/traberry/app version=master accept_hostkey=yes
       key_file=/home/traberry/.ssh/id_rsa
  tags:
    - app

- name: change permission to traberry:traberry
  shell: chown -R traberry:traberry /home/traberry/app
  tags:
    - app

- name: install modules with carton 
  sudo: yes
  sudo_user: traberry
  shell: chdir=/tmp (. ~/.bash_profile; cd /home/traberry/app; carton install)
  tags:
    - app


