---
- hosts: db-slave-hosts
  remote_user: root
  roles:
   - mysql 
  vars:
    mysql_root_db_pass: root_pass 
    mysql_port: 3306
    mysql_bind_address: "0.0.0.0"
    mysql_db_id: 2
    mysql_repl_role: slave
    mysql_repl_master: master_host_name 
    mysql_users:
      - name: a_user 
        pass: a_user_pass 
        priv: "hogehoge.*:ALL"
        host: app1
      - name: a_user2 
        pass: a_user_pass2
        priv: "hogehoge.*:ALL"
        host: app2
    mysql_db:
      - name: hogehoge 
    mysql_repl_user:
      - name: repel_user
        pass: repel_pass
