---
- hosts: sg-nginx-reverseproxy
  remote_user: root
  roles:
    - iptables-rp
    - bootstrap 
    - monit
    - nginx
  vars:
    upstream_name: YOUR_APP
    static_path: '/fbcdn/'
    static_rewrite:
      - '^/fbcdn/(.*)/(.*) http://$1.fbcdn.net/$2 break'
