---
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ hostvars[item].ansible_hostname }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address}} {{hostvars[item].ansible_hostname}}" state=present
  when:  hostvars[item].ansible_eth1.ipv4.address is defined
  with_items: groups['all']
